### ISSUE TITLE
Code implementation for Cuttlefish

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/htmltemplategenerator#23]
# Todo list before _Cuttlefish_ is complete
## Content
- [x] Content customization
- [x] Template selection and customization
## Libraries
- [x] Library loading
- [x] Library exclusion
- [x] Library customization
- [x] Library counter
## Metadata
- [x] Metadata tag implementation
- [x] Template selection and customization
## Resources
- [x] Resource loader for head
## Result/ Other
- [x] Warnings and error messages
- [x] Fiddle, pen, copy, copy minified buttons
- [x] Result tab writer
- [x] Base class for results
- [x] Errors for bad separation (not commas or not spaces etc.)
- [x] Commenter for the final result (commenter toggle on/off)
- [x] ~~Page statistics analyzer etc. (load times and page load in general might be of use)~~
