### ISSUE TITLE
v1.0.0 (Cuttlefish) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/htmltemplategenerator#24]
# List of changes and new features in _Cuttlefish_ (v1.0.0)

Based on the various issues opened about _Cuttlefish_, this is a collective roadmap with all the features and changes that need to be implemented before _Cuttlefish_ is ready for release.
## Interface changes and features
- [x] UI redesign, prioritize ease of use (see issue #7)
- [x] Add more options and easier customization for content and libraries
- [x] Body classes field
- [x] Notify user of changes in loading etc.
- [x] Warn user about problems with specific libraries and/or loaded files
- [x] Add more meta options, including toggles for generator, viewport, favicon tags and a toggle for old browser warnings
- [x] Implement code that applies UI choices to the template
- [x] Fiddle, Codepen, Minify buttons
- [x] Help section (see issue #19)
- [x] Commenter toggle(s)
- [x] Change to SemVer (see issue #20)
- [x] Turn `autocomplete` to `off` for all form elements to avoid problems with responsiveness
- [x] Add reset/clear button
- [x] Use Ace editor for results area
- [x] Add support for `normalize.css`
## Templates (see issues #12, #21)
- [x] Add options for simple pages, forms and error pages
- [x] Customization section for the template bases
- [x] Implement code for simple templates
- [x] Implement code for form templates
- [x] Implement code for error templates
- [x] Implement template stylist for _Bootstrap_
- [x] ~~Add navbar choice to all templates (Optional)~~
- [x] ~~Allow user to optionally specify a different title and content for the `page-template-min`~~
## Code refactoring (see issue #23)
- [x] Update to jQuery 3.1.0 (see issue #14)
- [x] Switch to SCSS (see issue #15)
- [x] ~~Change library loading to dynamic XML (see issues #13, #17)~~
- [x] Refactor XML loader to use Java object notation to improve speed, but keep the code modular
- [x] Implement library loading using a prototype
- [x] Load libraries to template
- [x] Add alerts for library requirements and load required libraries
- [x] Create a prototype for the generated template
- [x] Refactor generation code using prototype
- [x] Refactor export code using prototype
- [x] Make UI react to the user's choices
- [x] Implement export to JSFiddle and Codepen functionality - in new tab (see issue #16)
- [x] ~~Implement or use minifier for copy minified~~
- [x] ~~Implement template load analyzer (Optional)~~
- [x] Implement commenter
## Bug fixes
- [x] Fix bootstrap loading (see issue #11)
- [x] Fix bootstrap loading in JSFiddle (see issue #9)
- [x] JSFiddle loading scripts broken (see issue #8)
- [x] Bootstrap viewport meta tag missing (see issue #10)
- [x] ~~Fix ace editor bug with worker, which logs in console as error (On Hold)~~

**Comment by Chalarangelo** [comment]
8eb94d1: Commenter toggle, `autocomplete=off`, Ace editor, partial metadata tag implementation for generator, partial implementation for the copy button functionality, partial generator prototype.

**Comment by Chalarangelo** [comment]
6607b12: More code implemented, mostly addressing issue #23.

**Comment by Chalarangelo** [comment]
a9f0c2c: XML loader has been removed entirely, now using JS objects. The `addCSS()` and `addScript()` functions now return the object on which they are called, so that they can be called at initialization in sequence.

**Comment by Chalarangelo** [comment]
Navbar and `template-min` options have been discarded for this release.

**Comment by Chalarangelo** [comment]
7a609f6: Requirement loading is complete, the corresponding checkbox in the above list is marked as done. Alerts and warnings for requirements will be implemented alongside other alerts and requirements.

**Comment by Chalarangelo** [comment]
- Minifier has been discarded for the current release (and possibly for future releases as well), as it does not add anything crucial to the tool.
- Load analyzer has been discarded for this release.
- The Ace Editor bug is not causing any trouble yet, so we'll leave it be for the time being.

**Comment by Chalarangelo** [comment]
cd477df: Stable version, about to release. Minor changes and houskeeping might be needed still, as well as changing the README.md file.
