### ISSUE TITLE
v1.0.1 (hotfix) Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/htmltemplategenerator#26]
- [x] Squash the Codepen bug of issue #25 
- [x] Remove the gif files from the build
- [x] Add a modal dialog that shows the first time you use the app and stores a javascript string in local memory, so it does not pop up next time, until the next update
- [x] Update `gh-pages` to use minified versions of the javascript and css files
- [x] Add Pure.css to the libraries list
- [x] Update README.md to say **v1.0.1**
- [x] Update app to say **v1.0.1** and corresponding date of release

**Comment by Chalarangelo** [comment]
fee9edb: Deployed.
